//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgb.derby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public int RaceID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ScoringMethod { get; set; }
        public Nullable<int> Rounds { get; set; }
        public Nullable<int> Lanes { get; set; }
    }
}
